# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(369, 411)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Dialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(0, 340, 371, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.btnPac = QtWidgets.QPushButton(Dialog)
        self.btnPac.setGeometry(QtCore.QRect(20, 20, 121, 52))
        self.btnPac.setObjectName("btnPac")
        self.btnBlue = QtWidgets.QPushButton(Dialog)
        self.btnBlue.setGeometry(QtCore.QRect(20, 80, 121, 52))
        self.btnBlue.setObjectName("btnBlue")
        self.btnRed = QtWidgets.QPushButton(Dialog)
        self.btnRed.setGeometry(QtCore.QRect(20, 140, 121, 52))
        self.btnRed.setObjectName("btnRed")
        self.btnPurple = QtWidgets.QPushButton(Dialog)
        self.btnPurple.setGeometry(QtCore.QRect(20, 260, 121, 52))
        self.btnPurple.setObjectName("btnPurple")
        self.btnYellow = QtWidgets.QPushButton(Dialog)
        self.btnYellow.setGeometry(QtCore.QRect(20, 200, 121, 52))
        self.btnYellow.setObjectName("btnYellow")
        self.lblPac = QtWidgets.QLabel(Dialog)
        self.lblPac.setGeometry(QtCore.QRect(150, 20, 201, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPac.setFont(font)
        self.lblPac.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPac.setObjectName("lblPac")
        self.lblBlue = QtWidgets.QLabel(Dialog)
        self.lblBlue.setGeometry(QtCore.QRect(150, 80, 201, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblBlue.setFont(font)
        self.lblBlue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblBlue.setObjectName("lblBlue")
        self.lblRed = QtWidgets.QLabel(Dialog)
        self.lblRed.setGeometry(QtCore.QRect(150, 140, 201, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblRed.setFont(font)
        self.lblRed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRed.setObjectName("lblRed")
        self.lblYellow = QtWidgets.QLabel(Dialog)
        self.lblYellow.setGeometry(QtCore.QRect(150, 200, 201, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblYellow.setFont(font)
        self.lblYellow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblYellow.setObjectName("lblYellow")
        self.lblPurple = QtWidgets.QLabel(Dialog)
        self.lblPurple.setGeometry(QtCore.QRect(150, 260, 201, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPurple.setFont(font)
        self.lblPurple.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPurple.setObjectName("lblPurple")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Game XP - BizSys - Setup"))
        self.btnPac.setText(_translate("Dialog", "Pacman"))
        self.btnBlue.setText(_translate("Dialog", "Blue Ghost"))
        self.btnRed.setText(_translate("Dialog", "Red Ghost"))
        self.btnPurple.setText(_translate("Dialog", "Purple Ghost"))
        self.btnYellow.setText(_translate("Dialog", "Yellow Ghost"))
        self.lblPac.setText(_translate("Dialog", "0"))
        self.lblBlue.setText(_translate("Dialog", "0"))
        self.lblRed.setText(_translate("Dialog", "0"))
        self.lblYellow.setText(_translate("Dialog", "0"))
        self.lblPurple.setText(_translate("Dialog", "0"))

